esphome:
  name: metatool1

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  #manual_ip: 
    # Set this to the IP of the ESP
    #  static_ip: 192.168.1.201
    # Set this to the IP address of the router. Often ends with .1
    #gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Metatool1 Fallback Hotspot"
    password: "DJjwCeDQqMD1"

captive_portal:

  # Example configuration entry
web_server:
  port: 80


light:
  - platform: neopixelbus
    id: "neopixel_light"
    type: GRB
    variant: WS2812
    pin: GPIO48
    num_leds: 60
    name: "NeoPixel Light"

web_server:
  port: 80

light:
  - platform: neopixelbus
    id: "neopixel_light"
    type: GRB
    variant: WS2812
    pin: GPIO48
    num_leds: 60
    name: "NeoPixel Light"
    